### ISSUE TITLE
Can not pass data

### ISSUE THREAD

**Issue by gasparyanyur** [jmjuanes/electron-ejs#11]
Hi all. I am trying to pass data to inluced ejs tempalte.So in my `main.js` I have a code look like this
```
sendPostRequest('GET', 'user/get_accounts', {}, function (res) {
        res = JSON.parse(res);
        if (res.status === true) {

            var accounts = res.result.accounts;
            var currencies = res.result.currencies;

            var ejs = new electronEjs({accounts:accounts,currencies:currencies,a:'A'});

            showTemplate(APP.Templates.Account);
        }
    }, true); 
```

```
function showTemplate(template) {
    mainWindow.loadURL(url.format({
        pathname: path.join(__dirname, APP.TemplatesPath, template),
        protocol: 'file:',
        slashes: true
    }));
}
```

But after running app I am getting an error look like this
```
Uncaught Exception:
ReferenceError: /var/www/desktop-electron/templates/user/accounts.ejs:2
    1| <%- include('header'); -%>
 >> 2| <p><%= a %></p>
    3| <%- include('footer'); -%>
```

**Comment by jmjuanes** [comment]
Hi,

You can pass data to the `ejs` renderer, but only when you initialise the `electron-ejs` module. You can't pass new data each time you render a new `ejs` file, because this module adds events listeners that are triggered when the `loadUrl` is called. If you call multiple times the constructor of `electron-ejs`, only the data passed the first time will be used to render the `ejs` files.

The only solution that I found is that you call the `ejs` renderer manually and then load the generated HTML string, using [data url](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) (see https://github.com/electron/electron/issues/1146). But I think that is not a good solution...

A good solution may be using a single page application instead of a multi page application, and pass data between the main and the render using [ipcMain](https://electronjs.org/docs/api/ipc-main) and [ipcRenderer](https://electronjs.org/docs/api/ipc-renderer). You can use frameworks like **react** or **ember** to develop a SPA.

If you think that there is another solution to your issue and we can implement that in the `electron-ejs` module, tell me please.
