### ISSUE TITLE
Parsing URL doesnt work

### ISSUE THREAD

**Issue by gamelaster** [jmjuanes/electron-ejs#2]
![image](https://cloud.githubusercontent.com/assets/1665373/15270623/6a2c53de-1a26-11e6-819e-01bea4a424ae.png)
adding .substring(1) to file variable helped

**Comment by jmjuanes** [comment]
Hi @GAMELASTER 

I think that the problem is that you are loading the `.ejs` file with a relative path. Please, try to open the file using the Node.JS `__dirname` variable. For example: 

``` javascript
mainWindow.loadUrl('file://' + __dirname + '/index.ejs');
```

I think that with this the problem will be fixed. If not, please ask me again and we will find another solution.  

I am waiting your response.

:)

**Comment by gamelaster** [comment]
Hey, thanks for you fast reply! I sent a some pull request, so check it out! :-)
